services:
  - type: web
    name: reel-maker
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: JAMENDO_CLIENT_ID
        sync: false
      - key: GOOGLE_CSE_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
